services:
  shardworks:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: "6"
          memory: 6g
    extra_hosts:
      - "host.docker.internal:host-gateway"
    hostname: devcontainer
    ipc: host
    networks:
      - shardworks
    shm_size: 1g
    volumes:
      - ..:/workspace:cached
      - ${HOME}/.ssh/id_ed25519:/etc/coco/.ssh/id_ed25519:ro

networks:
  shardworks:
    driver: bridge

volumes:
  dolt-data:
